github: [Sian-Lee-SA]
buy_me_a_coffee: SianLee
custom: ["https://www.paypal.com/donate/?business=A82MM255CXF9L&no_recurring=0&item_name=Donating+will+help+justify+my+time+coding+and+doing+projects+that+also+benefits+others.+Any+amount+is+greatly+appreciated%21&currency_code=AUD"]
